# Generated by Django 3.1.4 on 2020-12-29 14:23

import coffee_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRangType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang_name', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('rang', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=70)),
                ('date_birth', models.DateField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_start_time', models.DateTimeField(blank=True, null=True)),
                ('discount_end_time', models.DateTimeField(blank=True, null=True)),
                ('discount_type', models.CharField(max_length=200)),
                ('discount_review', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=70)),
                ('package_price', models.IntegerField(blank=True)),
                ('package_desc', models.TextField(max_length=100)),
                ('package_volumn', models.IntegerField(blank=True)),
                ('package_avarage_weight', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('package_images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('info', models.TextField(max_length=300)),
                ('stock', models.BooleanField()),
                ('exp_date', models.DateTimeField()),
                ('product_size', models.PositiveSmallIntegerField()),
                ('product_weight', models.PositiveSmallIntegerField()),
                ('category', models.ManyToManyField(blank=True, to='coffee_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=80)),
                ('store_phone', models.CharField(max_length=13)),
                ('store_address', models.CharField(max_length=150)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('during', models.DateTimeField()),
                ('ended', models.BooleanField()),
                ('action_rang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.actionrangtype')),
                ('action_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.actiontype')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True)),
                ('price', models.FloatField()),
                ('location', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discount_id', models.ManyToManyField(blank=True, to='coffee_app.Discount')),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.package')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.product')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=400)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.product')),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.store')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', coffee_app.models.IntegerRangeField(blank=True)),
                ('store_rating', coffee_app.models.IntegerRangeField(blank=True)),
                ('delivery_rating', coffee_app.models.IntegerRangeField(blank=True)),
                ('package_rating', coffee_app.models.IntegerRangeField(blank=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.store'),
        ),
        migrations.AddField(
            model_name='discount',
            name='products_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.store'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.PositiveSmallIntegerField(blank=True)),
                ('date', models.DateField()),
                ('during', models.DateTimeField()),
                ('delivery_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.ratings')),
                ('delivery_type', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.deliverytype')),
                ('package_id', models.ManyToManyField(blank=True, to='coffee_app.Package')),
                ('product_id', models.ManyToManyField(blank=True, to='coffee_app.Product')),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.store')),
                ('trade_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.trade')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_app.customer')),
            ],
        ),
    ]
